export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const INCREMENT_DELAY = 'INCREMENT_DELAY';
export const DUMMY_ACTION = 'DUMMY_ACTION';